# ==========================================
# 1. IMPORTACIONES
# ==========================================

In [1]:
from sqlalchemy import create_engine, text
import sqlalchemy
import mysql.connector as mysql
import pandas as pd
import os

# ==========================================
# 1.1. PARÁMETROS DE CONEXIÓN
# ==========================================

In [2]:

user = 'root'
password = 'password'
sqlServer = 'localhost'
database_name = "NUCLIO"

connStr = f"mysql+mysqlconnector://{user}:{password}@{sqlServer}"
print(connStr)

engine_server = create_engine(connStr)
conn = engine_server.connect()
conn.execute(text(f"CREATE DATABASE IF NOT EXISTS {database_name}"))
conn.commit()
conn.close()

connStr_db = f"mysql+mysqlconnector://{user}:{password}@{sqlServer}/{database_name}"
engine = create_engine(connStr_db)
conn = engine.connect()

mysql+mysqlconnector://root:password@localhost

# ==========================================
# 1.2 CREACIÓN DE TABLAS 
# ==========================================

In [ ]:
conn.execute(text("""
CREATE TABLE IF NOT EXISTS ALOJAMIENTO (
    CODIGO_ALOJAMIENTO VARCHAR(20) PRIMARY KEY,
    NOMBRE VARCHAR(255),
    CANT_BANYOS INT,
    CANT_HAB INT,
    SALON ENUM('SI','NO'),
    TERRAZA ENUM('SI','NO'),
    AIREC_ACOND ENUM('SI','NO'), #me doy cuenta posteriormente de una errata al definir la columna, lo dejo así para no dropear tabla y tener que volver a crearla
    PISCINA ENUM('SI','NO'),
    SUPERFICIE FLOAT)"""))
conn.commit()

conn.execute(text("""
CREATE TABLE IF NOT EXISTS UBICACION (
    CODIGO_ALOJAMIENTO VARCHAR(20) PRIMARY KEY,
    PAIS VARCHAR(50),
    CIUDAD VARCHAR(50),
    DIST_METRO FLOAT,
    DIST_CENTRO FLOAT)"""))
conn.commit()

conn.execute(text("""
CREATE TABLE IF NOT EXISTS PRECIO (
    CODIGO_ALOJAMIENTO VARCHAR(20) PRIMARY KEY,
    PRECIO FLOAT,
    PORCENTAJE_RESERVA FLOAT)"""))
conn.commit()

conn.execute(text("""
CREATE TABLE IF NOT EXISTS PUNTUACION (
    CODIGO_ALOJAMIENTO VARCHAR(20) PRIMARY KEY,
    PUNTOS_ALOJAMIENTO FLOAT,
    PUNTOS_AGENCIA FLOAT)"""))
conn.commit()

# ==========================================
# 1.3 CARGA DE DATOS
# ==========================================

In [4]:
print(os.getcwd())

/home/sergi/sql-work

In [5]:
df_alojamiento = pd.read_excel("/home/sergi/sql-work/Ficheros-20260126/ALOJAMIENTO.xlsx")
df_alojamiento.to_sql("ALOJAMIENTO", engine, if_exists="replace")

df_ubicacion = pd.read_excel("/home/sergi/sql-work/Ficheros-20260126/UBICACION.xlsx")
df_ubicacion.to_sql("UBICACION", engine, if_exists="replace")

df_precio = pd.read_excel("/home/sergi/sql-work/Ficheros-20260126/PRECIO.xlsx")
df_precio.to_sql("PRECIO", engine, if_exists="replace")

df_puntuacion = pd.read_excel("/home/sergi/sql-work/Ficheros-20260126/PUNTUACION.xlsx")
df_puntuacion.to_sql("PUNTUACION", engine, if_exists="replace")

20

In [6]:
df_alojamiento.head()

,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,ALOJ002,Apartamento Las Palmeras,1,2,SI,NO,SI,NO,75
2,ALOJ003,Cabaña El Refugio,1,1,NO,SI,NO,NO,45
3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90
4,ALOJ005,Estudio Playa Blanca,1,1,NO,NO,SI,NO,40

In [7]:
df_ubicacion.head()

  CODIGO_ALOJAMIENTO      PAIS     CIUDAD  DIST_METRO  DIST_CENTRO
0            ALOJ001  Portugal      Liboa         1.0          2.0
1            ALOJ002    España     Madrid         0.5          0.8
2            ALOJ003    España  Barcelona         0.9          0.4
3            ALOJ004   Francia   Marsella         3.0          4.0
4            ALOJ005  Portugal     Oporto         4.0          3.0

In [8]:
df_precio.head()

  CODIGO_ALOJAMIENTO  PRECIO_ALQUILER RESERVA  PORCENTAJE_RESERVA
0            ALOJ001             1800      SI                 100
1            ALOJ002              780      SI                  25
2            ALOJ003              800      NO                   0
3            ALOJ004             1600      SI                  25
4            ALOJ005              900      NO                   0

In [9]:
df_puntuacion.head()

  CODIGO_ALOJAMIENTO  PUNTOS       AGENCIA  PUNTOS_AGENCIA
0            ALOJ001     5.0    GlobalHome             4.4
1            ALOJ002     4.2    AndesRenta             4.1
2            ALOJ003     4.1  AlquilaFacil             4.0
3            ALOJ004     4.6    CaribeRent             4.6
4            ALOJ005     4.4      RentaTop             3.8

# ==========================================
# 2. PRIMERA PARTE
# ==========================================

### 2.1 El cliente exige terraza y aire acondicionado, pero no quiere piscina

In [21]:
df_alojamiento.head(2)

,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,ALOJ002,Apartamento Las Palmeras,1,2,SI,NO,SI,NO,75

In [89]:
q1 = text("""SELECT * FROM ALOJAMIENTO
          WHERE TERRAZA = 'SI' AND
          AIREC_ACOND = 'SI' AND
          PISCINA = 'NO'""");
qq1 =  pd.read_sql(q1, conn)
qq1

,index,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90
1,9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88
2,14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120
3,17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100

### 2.2 No se alojará en estudios que no tengan salón ni en propiedades con solo un baño

In [81]:
q2 = text("""SELECT * FROM ALOJAMIENTO
          WHERE SALON = 'SI' AND
          CANT_BANYOS > 1""");
qq2 =  pd.read_sql(q2, conn)
qq2

,index,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90
2,5,ALOJ006,Chalet Vista al Lago,3,4,SI,SI,SI,SI,150
3,6,ALOJ007,Dúplex Jardines del Sur,2,3,SI,SI,SI,SI,130
4,8,ALOJ009,Casa Rústica Montaña,2,2,SI,SI,NO,NO,85
5,9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88
6,11,ALOJ012,Villa Palmeras,2,3,SI,SI,SI,SI,110
7,13,ALOJ014,Casa del Mar,3,4,SI,SI,SI,SI,160
8,14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120
9,16,ALOJ017,Chalet Jardín Secreto,3,5,SI,SI,SI,SI,180
10,17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100
11,18,ALOJ019,Casa Río Claro,2,2,SI,SI,NO,NO,95

### 2.3 La propiedad debe tener como mínimo 80m2

In [80]:
q3 = text(""" SELECT * FROM ALOJAMIENTO
          WHERE SUPERFICIE >= 80""");
qq3 =  pd.read_sql(q3, conn)
qq3

,index,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90
2,5,ALOJ006,Chalet Vista al Lago,3,4,SI,SI,SI,SI,150
3,6,ALOJ007,Dúplex Jardines del Sur,2,3,SI,SI,SI,SI,130
4,8,ALOJ009,Casa Rústica Montaña,2,2,SI,SI,NO,NO,85
5,9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88
6,11,ALOJ012,Villa Palmeras,2,3,SI,SI,SI,SI,110
7,12,ALOJ013,Apartamento Moderno,1,2,SI,NO,SI,NO,80
8,13,ALOJ014,Casa del Mar,3,4,SI,SI,SI,SI,160
9,14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120
10,16,ALOJ017,Chalet Jardín Secreto,3,5,SI,SI,SI,SI,180
11,17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100
12,18,ALOJ019,Casa Río Claro,2,2,SI,SI,NO,NO,95

### 2.4 Como el cliente odia el ruido, no quiere alojarse en propiedades a menos de 1 km de una estación de metro ni a menos de 2 km del centro

In [25]:
df_alojamiento.head(2)

,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,ALOJ002,Apartamento Las Palmeras,1,2,SI,NO,SI,NO,75

In [26]:
df_ubicacion.head(2)

  CODIGO_ALOJAMIENTO      PAIS  CIUDAD  DIST_METRO  DIST_CENTRO
0            ALOJ001  Portugal   Liboa         1.0          2.0
1            ALOJ002    España  Madrid         0.5          0.8

In [78]:
q4 = text("""SELECT * FROM ALOJAMIENTO x
          JOIN UBICACION y ON y.CODIGO_ALOJAMIENTO = x.CODIGO_ALOJAMIENTO
          WHERE y.DIST_METRO > 1 AND y.DIST_CENTRO >2""");
qq4 =  pd.read_sql(q4, conn)
qq4

,index,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE,index,CODIGO_ALOJAMIENTO,PAIS,CIUDAD,DIST_METRO,DIST_CENTRO
0,3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90,3,ALOJ004,Francia,Marsella,3.0,4.0
1,4,ALOJ005,Estudio Playa Blanca,1,1,NO,NO,SI,NO,40,4,ALOJ005,Portugal,Oporto,4.0,3.0
2,7,ALOJ008,Loft Urbano,1,1,SI,NO,SI,NO,60,7,ALOJ008,España,Barcelona,2.0,3.0
3,8,ALOJ009,Casa Rústica Montaña,2,2,SI,SI,NO,NO,85,8,ALOJ009,España,Madrid,2.0,4.0
4,9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88,9,ALOJ010,España,Bilbao,2.0,5.0
5,14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120,14,ALOJ015,España,Málaga,2.0,4.0
6,17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100,17,ALOJ018,España,Ibiza,2.0,4.0

### 2.5 El rango permitido por el cliente para pagar es entre 1.500€ y 2.000€ la noche.

In [30]:
df_precio.head(2)

  CODIGO_ALOJAMIENTO  PRECIO_ALQUILER RESERVA  PORCENTAJE_RESERVA
0            ALOJ001             1800      SI                 100
1            ALOJ002              780      SI                  25

In [79]:
q5= text("""SELECT * FROM ALOJAMIENTO x
JOIN PRECIO y ON y.CODIGO_ALOJAMIENTO = x.CODIGO_ALOJAMIENTO
WHERE y.PRECIO_ALQUILER > 1500 AND y.PRECIO_ALQUILER <2000""");
qq5 =  pd.read_sql(q5, conn)
qq5

,index,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE,index,CODIGO_ALOJAMIENTO,PRECIO_ALQUILER,RESERVA,PORCENTAJE_RESERVA
0,0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120,0,ALOJ001,1800,SI,100
1,3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90,3,ALOJ004,1600,SI,25
2,8,ALOJ009,Casa Rústica Montaña,2,2,SI,SI,NO,NO,85,8,ALOJ009,1600,SI,100
3,9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88,9,ALOJ010,1750,SI,25
4,10,ALOJ011,Cabaña Bosque Encantado,1,2,NO,SI,NO,NO,65,10,ALOJ011,1825,NO,0
5,11,ALOJ012,Villa Palmeras,2,3,SI,SI,SI,SI,110,11,ALOJ012,1750,NO,0
6,12,ALOJ013,Apartamento Moderno,1,2,SI,NO,SI,NO,80,12,ALOJ013,1652,NO,0
7,13,ALOJ014,Casa del Mar,3,4,SI,SI,SI,SI,160,13,ALOJ014,1941,NO,0
8,14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120,14,ALOJ015,1800,SI,25
9,17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100,17,ALOJ018,1900,SI,25
10,18,ALOJ019,Casa Río Claro,2,2,SI,SI,NO,NO,95,18,ALOJ019,1570,NO,0
11,19,ALOJ020,Loft Estación Norte,1,1,SI,NO,SI,NO,55,19,ALOJ020,1580,NO,0

### 2.6 Como en anteriores ocasiones ha tenido problemas de intentos de estafas con otras agencias, el cliente pide que el % de reserva no sea muy alto, pero tampoco tan bajo (porque le genera inseguridad) por lo que propone un 25%

In [77]:
q6= text("""SELECT * FROM ALOJAMIENTO x
         JOIN PRECIO y ON y.CODIGO_ALOJAMIENTO = x.CODIGO_ALOJAMIENTO
         WHERE y.PORCENTAJE_RESERVA = 25""");
qq6 =  pd.read_sql(q6, conn)
qq6

,index,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE,index,CODIGO_ALOJAMIENTO,PRECIO_ALQUILER,RESERVA,PORCENTAJE_RESERVA
0,1,ALOJ002,Apartamento Las Palmeras,1,2,SI,NO,SI,NO,75,1,ALOJ002,780,SI,25
1,3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90,3,ALOJ004,1600,SI,25
2,7,ALOJ008,Loft Urbano,1,1,SI,NO,SI,NO,60,7,ALOJ008,1500,SI,25
3,9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88,9,ALOJ010,1750,SI,25
4,14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120,14,ALOJ015,1800,SI,25
5,17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100,17,ALOJ018,1900,SI,25

### 2.7 Quiere que el alojamiento tenga más de 4,5 puntos de confianza y que la agencia que lo lleva tenga más de 4 puntos

In [35]:
df_puntuacion.head(2)

  CODIGO_ALOJAMIENTO  PUNTOS     AGENCIA  PUNTOS_AGENCIA
0            ALOJ001     5.0  GlobalHome             4.4
1            ALOJ002     4.2  AndesRenta             4.1

In [76]:
q7= text("""SELECT * FROM ALOJAMIENTO x
         JOIN PUNTUACION y ON y.CODIGO_ALOJAMIENTO = x.CODIGO_ALOJAMIENTO
         WHERE y.PUNTOS > 4.5 AND y.PUNTOS_AGENCIA > 4""");
qq7 =  pd.read_sql(q7, conn)
qq7

,index,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE,index,CODIGO_ALOJAMIENTO,PUNTOS,AGENCIA,PUNTOS_AGENCIA
0,0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120,0,ALOJ001,5.0,GlobalHome,4.4
1,3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90,3,ALOJ004,4.6,CaribeRent,4.6
2,6,ALOJ007,Dúplex Jardines del Sur,2,3,SI,SI,SI,SI,130,6,ALOJ007,4.9,SevillaRooms,4.5
3,7,ALOJ008,Loft Urbano,1,1,SI,NO,SI,NO,60,7,ALOJ008,4.8,ChileVive,4.3
4,8,ALOJ009,Casa Rústica Montaña,2,2,SI,SI,NO,NO,85,8,ALOJ009,4.7,MexicoRent,4.8
5,9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88,9,ALOJ010,4.8,UYAlquila,4.9
6,13,ALOJ014,Casa del Mar,3,4,SI,SI,SI,SI,160,13,ALOJ014,4.7,BogotaLodge,4.5
7,14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120,14,ALOJ015,4.9,EasyStay Valencia,4.7
8,16,ALOJ017,Chalet Jardín Secreto,3,5,SI,SI,SI,SI,180,16,ALOJ017,4.9,CuscoRenta,4.4
9,17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100,17,ALOJ018,4.7,MendozaRooms,4.7
10,18,ALOJ019,Casa Río Claro,2,2,SI,SI,NO,NO,95,18,ALOJ019,4.9,GDLRent,4.2
11,19,ALOJ020,Loft Estación Norte,1,1,SI,NO,SI,NO,55,19,ALOJ020,4.9,VivaStay,4.9

### 2.8 Crear en una única query la combinación de los filtros anteriores para hallar las propiedades que finalmente cumplen con todas las exigencias del cliente

In [ ]:
q8 = text("""SELECT * FROM ALOJAMIENTO x
          JOIN UBICACION y ON y.CODIGO_ALOJAMIENTO = x.CODIGO_ALOJAMIENTO
          JOIN PRECIO z ON z.CODIGO_ALOJAMIENTO = y.CODIGO_ALOJAMIENTO
          JOIN PUNTUACION a ON a.CODIGO_ALOJAMIENTO = z.CODIGO_ALOJAMIENTO
          WHERE x.TERRAZA = 'SI' AND
          x.AIREC_ACOND = 'SI' AND
          x.PISCINA = 'NO' AND
          x.SALON = 'SI' AND
          x.CANT_BANYOS > 1 AND
          x.SUPERFICIE >= 80 AND
          y.DIST_METRO > 1 AND 
          y.DIST_CENTRO >2 AND
          z.PRECIO_ALQUILER > 1500 AND 
          z.PRECIO_ALQUILER <2000 AND
          z.PORCENTAJE_RESERVA = 25 AND
          a.PUNTOS > 4.5 AND 
          a.PUNTOS_AGENCIA > 4""");

In [49]:
query = pd.read_sql(q8, conn)
query = query.drop(columns=["index"])
query = query.loc[:, ~query.columns.duplicated()]
query

,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE,PAIS,CIUDAD,DIST_METRO,DIST_CENTRO,PRECIO_ALQUILER,RESERVA,PORCENTAJE_RESERVA,PUNTOS,AGENCIA,PUNTOS_AGENCIA
0,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90,Francia,Marsella,3.0,4.0,1600,SI,25,4.6,CaribeRent,4.6
1,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88,España,Bilbao,2.0,5.0,1750,SI,25,4.8,UYAlquila,4.9
2,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120,España,Málaga,2.0,4.0,1800,SI,25,4.9,EasyStay Valencia,4.7
3,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100,España,Ibiza,2.0,4.0,1900,SI,25,4.7,MendozaRooms,4.7

### 2.9 Como habéis visto, tenemos 4 propiedades que cumplen con todas las exigencias de nuestro cliente, ahora bien, desde tu punto de vista, haciendo un análisis de los datos del cliente y de todas sus exigencias ¿Cuál de estos 4 alojamientos le recomendarías y por qué?

Le recomendaría el Alojamiento de Marsella. El tipo quiere alejarse del foco mediático lo máximo posible, así que lo mejor es que no esté en España. Marsella tiene playa, es el sur de Francia, hace buen tiempo y tiene todas las características que ha pedido. Málaga e Ibiza las descarto automáticamente porque son un hervidero en verano, y Bilbao es buena opción pero, para que el retiro sea aún más anónimo, es mejor que no esté en el país.


# ==========================================
# 3. SEGUNDA PARTE
# ==========================================

### 3.1 ¿Cuál es la suma total de metros cuadrados de los alojamientos que tienen piscina?

In [50]:
df_alojamiento.head(2)

,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,ALOJ002,Apartamento Las Palmeras,1,2,SI,NO,SI,NO,75

In [75]:
q9 = text("""SELECT SUM(SUPERFICIE) as TOTAL_M2 FROM ALOJAMIENTO 
      WHERE PISCINA = 'SI'""");
qq9 =  pd.read_sql(q9, conn)
qq9

   TOTAL_M2
0     850.0

### 3.2 ¿Cuál es el alojamiento con mayor superficie?

In [73]:
q10 = text("""SELECT * FROM ALOJAMIENTO
           ORDER BY SUPERFICIE DESC
           LIMIT 1""");
qq10 =  pd.read_sql(q10, conn)
qq10

,index,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,16,ALOJ017,Chalet Jardín Secreto,3,5,SI,SI,SI,SI,180

### 3.3 ¿Cuál es el alojamiento con menor superficie?

In [72]:
q11 = text("""SELECT * FROM ALOJAMIENTO
           ORDER BY SUPERFICIE ASC
           LIMIT 1""");
qq11 =  pd.read_sql(q11, conn)
qq11

,index,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,15,ALOJ016,Estudio Urbano,1,1,NO,NO,SI,NO,35

### 3.4 ¿Cuántos alojamientos tienen salón?

In [71]:
q12 = text("""SELECT COUNT(*) as NUM_SALONES FROM ALOJAMIENTO 
WHERE SALON = 'SI'""");
qq12 =  pd.read_sql(q12, conn)
qq12

   NUM_SALONES
0           16

### 3.5 ¿Cuántos alojamientos tienen terraza?

In [70]:
q13 = text("""SELECT COUNT(*) as NUM_TERRAZAS FROM ALOJAMIENTO 
WHERE TERRAZA = 'SI'""");
qq13 =  pd.read_sql(q13, conn)
qq13

   NUM_TERRAZAS
0            14

### 3.6 ¿Cuántos alojamientos hay por cada país según nuestra tabla de UBICACIÓN?

In [62]:
df_ubicacion.head(2)

  CODIGO_ALOJAMIENTO      PAIS  CIUDAD  DIST_METRO  DIST_CENTRO
0            ALOJ001  Portugal   Liboa         1.0          2.0
1            ALOJ002    España  Madrid         0.5          0.8

In [68]:
q14 = text("""SELECT PAIS, COUNT(*) as NUM_ALOJ FROM ALOJAMIENTO x
       JOIN UBICACION y ON y.CODIGO_ALOJAMIENTO = x.CODIGO_ALOJAMIENTO
       GROUP BY PAIS""");
qq14 = pd.read_sql(q14, conn)
qq14

       PAIS  NUM_ALOJ
0  Portugal         4
1    España         8
2   Francia         4
3    Italia         4

### 3.7 ¿Cuál es el promedio de precios de alquiler de todos los alojamientos según la tabla PRECIO?

In [61]:
df_precio.head(2)

  CODIGO_ALOJAMIENTO  PRECIO_ALQUILER RESERVA  PORCENTAJE_RESERVA
0            ALOJ001             1800      SI                 100
1            ALOJ002              780      SI                  25

In [66]:
q15 = text("""SELECT AVG(PRECIO_ALQUILER) as AVG_PRECIO FROM PRECIO""");
qq15 = pd.read_sql(q15, conn);
qq15

   AVG_PRECIO
0      1568.4

### 3.8 ¿Cuáles son las 3 agencias que tienen la mayor puntuación de agencia (campo a usar: PUNTOS_AGENCIA) según la tabla PUNTUACION?

In [83]:
df_puntuacion.head(2)

  CODIGO_ALOJAMIENTO  PUNTOS     AGENCIA  PUNTOS_AGENCIA
0            ALOJ001     5.0  GlobalHome             4.4
1            ALOJ002     4.2  AndesRenta             4.1

In [90]:
q16 = text("""SELECT * FROM PUNTUACION
ORDER BY PUNTOS_AGENCIA DESC LIMIT 3""");
qq16 =  pd.read_sql(q16, conn)
qq16

   index CODIGO_ALOJAMIENTO  PUNTOS        AGENCIA  PUNTOS_AGENCIA
0      9            ALOJ010     4.8      UYAlquila             4.9
1      5            ALOJ006     4.3     TerraHouse             4.9
2     10            ALOJ011     4.0  MalagaTurismo             4.9

### 3.9 Muestra los alojamientos (código y nombre) que: Contengan la palabra ‘Piso’ en su nombre o que tengan piscina y aire acondicionado, pero no pasen los 150 metros de superficie o que tengan más de un baño

In [91]:
df_alojamiento.head(2)

,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,ALOJ002,Apartamento Las Palmeras,1,2,SI,NO,SI,NO,75

In [95]:
q17 = text("""SELECT CODIGO_ALOJAMIENTO, NOMBRE FROM ALOJAMIENTO
           WHERE NOMBRE LIKE '%Piso%' OR
           (PISCINA = 'SI' AND
           AIREC_ACOND = 'SI' AND
           SUPERFICIE <= 150) OR
           (CANT_BANYOS > 1)""")
qq17 = pd.read_sql(q17, conn)
qq17

   CODIGO_ALOJAMIENTO                   NOMBRE
0             ALOJ001        Villa Sol del Mar
1             ALOJ004    Piso Centro Histórico
2             ALOJ006     Chalet Vista al Lago
3             ALOJ007  Dúplex Jardines del Sur
4             ALOJ009     Casa Rústica Montaña
5             ALOJ010            Ático del Sol
6             ALOJ012           Villa Palmeras
7             ALOJ014             Casa del Mar
8             ALOJ015         Dúplex Las Rocas
9             ALOJ017    Chalet Jardín Secreto
10            ALOJ018      Piso Parque Central
11            ALOJ019           Casa Río Claro

### 3.10 Muestra una consulta que muestre el código de alojamiento, el nombre, el precio y una columna donde veamos el precio del alquiler con el símbolo del euro al final de cada importe, esta nueva columna se debe llama PRECIO_MODIF

In [96]:
df_precio.head(2)

  CODIGO_ALOJAMIENTO  PRECIO_ALQUILER RESERVA  PORCENTAJE_RESERVA
0            ALOJ001             1800      SI                 100
1            ALOJ002              780      SI                  25

In [97]:
q18 = text("""SELECT x.CODIGO_ALOJAMIENTO, y.NOMBRE, x.PRECIO_ALQUILER, CONCAT(PRECIO_ALQUILER, '€') AS PRECIO_MODIF FROM PRECIO x
           JOIN ALOJAMIENTO y ON y.CODIGO_ALOJAMIENTO = x.CODIGO_ALOJAMIENTO""")
qq18 = pd.read_sql(q18, conn)
qq18

   CODIGO_ALOJAMIENTO                    NOMBRE  PRECIO_ALQUILER PRECIO_MODIF
0             ALOJ001         Villa Sol del Mar             1800        1800€
1             ALOJ002  Apartamento Las Palmeras              780         780€
2             ALOJ003         Cabaña El Refugio              800         800€
3             ALOJ004     Piso Centro Histórico             1600        1600€
4             ALOJ005      Estudio Playa Blanca              900         900€
5             ALOJ006      Chalet Vista al Lago             1200        1200€
6             ALOJ007   Dúplex Jardines del Sur             1300        1300€
7             ALOJ008               Loft Urbano             1500        1500€
8             ALOJ009      Casa Rústica Montaña             1600        1600€
9             ALOJ010             Ático del Sol             1750        1750€
10            ALOJ011   Cabaña Bosque Encantado             1825        1825€
11            ALOJ012            Villa Palmeras             1750        1750€
12            ALOJ013       Apartamento Moderno             1652        1652€
13            ALOJ014              Casa del Mar             1941        1941€
14            ALOJ015          Dúplex Las Rocas             1800        1800€
15            ALOJ016            Estudio Urbano             2000        2000€
16            ALOJ017     Chalet Jardín Secreto             2120        2120€
17            ALOJ018       Piso Parque Central             1900        1900€
18            ALOJ019            Casa Río Claro             1570        1570€
19            ALOJ020       Loft Estación Norte             1580        1580€

### 3.11 Muestra una columna sobre la tabla PRECIO que se llame CATEGORIA_PRECIO y que indique la palabra ‘Bajo’ si el precio está entre 780 y 1000, ‘Medio’ si el precio está entre 1000 y 1700 y ‘Alto’ si es mayor a 1700

In [98]:
df_precio.head(2)

  CODIGO_ALOJAMIENTO  PRECIO_ALQUILER RESERVA  PORCENTAJE_RESERVA
0            ALOJ001             1800      SI                 100
1            ALOJ002              780      SI                  25

In [99]:
q19 = text("""SELECT CASE 
            WHEN PRECIO_ALQUILER > 780 AND PRECIO_ALQUILER < 1000 THEN 'BAJO'
            WHEN PRECIO_ALQUILER > 1000 AND PRECIO_ALQUILER < 1700 THEN 'MEDIO'
            ELSE 'ALTO'
            END AS CATEGORIA_PRECIO
            FROM PRECIO""")
qq19 = pd.read_sql(q19, conn)
qq19

   CATEGORIA_PRECIO
0              ALTO
1              ALTO
2              BAJO
3             MEDIO
4              BAJO
5             MEDIO
6             MEDIO
7             MEDIO
8             MEDIO
9              ALTO
10             ALTO
11             ALTO
12            MEDIO
13             ALTO
14             ALTO
15             ALTO
16             ALTO
17             ALTO
18            MEDIO
19            MEDIO